stages:
  - build
build:
  stage: build
  script:
    - mkdir _build
    - python3 -m venv _build/venv
    - source _build/venv/bin/activate # Enter virtual environment
    - >-
      export PIP_EXTRA_INDEX_URL="
      https://git.karmakrafts.dev/api/v4/projects/136/packages/pypi/simple 
      https://git.karmakrafts.dev/api/v4/projects/277/packages/pypi/simple 
      https://git.karmakrafts.dev/api/v4/projects/278/packages/pypi/simple
      "
    - pip3 install -r requirements.txt
    - sphinx-build . _build/html
    - deactivate # Exit virtual environment
    - mv -f _build/html _build/ferrous-docs
    - cp -r _build/ferrous-docs /var/www
  only:
    - master
  tags:
    - linux

