stages:
  - build
build:
  stage: build
  script:
    - mkdir _build
    - python3 -m venv _build/venv
    - source _build/venv/bin/activate # Enter virtual environment
    - >- 
      pip3 install -r requirements.txt 
      --extra-index-url https://git.karmakrafts.dev/api/v4/projects/136/packages/pypi/simple # Vanadium
      --extra-index-url https://git.karmakrafts.dev/api/v4/projects/277/packages/pypi/simple # Ferrous Pygmennts
      --extra-index-url https://git.karmakrafts.dev/api/v4/projects/278/packages/pypi/simple # Sphinx RTD Dark
    - sphinx-build . _build/html
    - deactivate # Exit virtual environment
    - mv -f _build/html _build/ferrous-docs
    - cp -r _build/ferrous-docs /var/www
  only:
    - master
  tags:
    - linux

